import React, { useState } from 'react';
import { Creator } from '../types';
import { Edit2, Trash2, Search, Download, Plus, User, ExternalLink } from 'lucide-react';
import { saveCreator, deleteCreator } from '../services/storageService';

interface CreatorListProps {
  creators: Creator[];
  currentUser?: string;
}

const CreatorList: React.FC<CreatorListProps> = ({ creators, currentUser }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [isModalOpen, setIsModalOpen] = useState(false);
  // Simplify editing for this list view, assumes full editing happens elsewhere or implemented simply here
  
  const filteredCreators = creators.filter(c => 
    c.name.toLowerCase().includes(searchTerm.toLowerCase()) || 
    c.username.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleDelete = async (id: string, name: string) => {
    if (window.confirm(`Are you sure you want to delete ${name}?`)) {
      await deleteCreator(id, name);
    }
  };

  // --- EXPORT LOGIC ---
  const handleExportExcel = () => {
    const generateDate = new Date().toLocaleString();
    const dateStr = new Date().toISOString().split('T')[0];

    // CSS Styles for the Excel file
    const tableStyle = `
      <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #ffffff; }
        .header-container { padding: 20px 0; border-bottom: 3px solid #6d28d9; margin-bottom: 20px; }
        .brand-text { color: #4c1d95; font-size: 28px; font-weight: 900; margin: 0; text-transform: uppercase; }
        .campaign-text { color: #000000; font-size: 16px; font-weight: bold; margin-top: 5px; }
        .meta-data { color: #374151; font-size: 11px; margin-top: 15px; font-family: monospace; }
        table { border-collapse: collapse; width: 100%; border: 1px solid #e5e7eb; }
        th { background-color: #4c1d95; color: white; padding: 12px 10px; font-weight: bold; font-size: 11px; }
        td { border: 1px solid #e5e7eb; padding: 8px 10px; font-size: 11px; }
        .num { text-align: right; font-family: 'Courier New', monospace; font-weight: bold; }
        .product-col { background-color: #f5f3ff; color: #4c1d95; font-weight: bold; }
      </style>
    `;

    const tableRows = creators.map(c => {
      let maikalianViews = 0, curtainViews = 0, tshirtViews = 0;
      if (c.uploads) {
        c.uploads.forEach(u => {
            if (u.product === 'Maikalian') maikalianViews += u.views;
            if (u.product === 'Xmas Curtain') curtainViews += u.views;
            if (u.product === 'Tshirt') tshirtViews += u.views;
        });
      }
      return `
      <tr>
        <td style="font-weight:bold; font-size: 12px;">${c.name}</td>
        <td>${c.username || '-'}</td>
        <td>${c.niche}</td>
        <td class="num product-col">${maikalianViews.toLocaleString()}</td>
        <td class="num product-col">${curtainViews.toLocaleString()}</td>
        <td class="num product-col">${tshirtViews.toLocaleString()}</td>
        <td class="num">${c.avgLikes.toLocaleString()}</td>
        <td class="num">${c.avgViews.toLocaleString()}</td>
        <td class="num">${c.videosCount}</td>
      </tr>
    `}).join('');

    const htmlContent = `
      <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
      <head>
        <meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8">
        ${tableStyle}
      </head>
      <body>
        <div class="header-container">
          <div class="brand-text">Global Media Live</div>
          <div class="campaign-text">A.I Content Campaign Monitoring</div>
          <div class="meta-data">Generated by : GML_System | Date: ${generateDate}</div>
        </div>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Username</th>
              <th>Niche</th>
              <th>Maikalian Views</th>
              <th>Curtain Views</th>
              <th>Tshirt Views</th>
              <th>Total Likes</th>
              <th>Total Views</th>
              <th>Uploaded</th>
            </tr>
          </thead>
          <tbody>${tableRows}</tbody>
        </table>
      </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: 'application/vnd.ms-excel' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `GML_Creator_Report_${dateStr}.xls`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportCSV = () => {
    const headers = ['Name', 'Username', 'Niche', 'Category', 'Total Views', 'Total Likes', 'Total Comments', 'Total Shares', 'Total Videos'];
    const csvContent = [
      headers.join(','),
      ...creators.map(c => [
        `"${c.name}"`, `"${c.username}"`, `"${c.niche}"`, `"${c.productCategory}"`,
        c.avgViews, c.avgLikes, c.avgComments, c.avgShares || 0, c.videosCount
      ].join(','))
    ].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `backup_${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-center gap-4 bg-gray-800 p-6 rounded-xl border border-gray-700">
        <div>
          <h2 className="text-xl font-bold text-white">Creator Database</h2>
          <p className="text-gray-400 text-sm">Manage influencers and track performance.</p>
        </div>
        <div className="flex gap-3">
            <button onClick={handleExportExcel} className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg font-bold text-sm">
                <Download className="w-4 h-4"/> Export Report
            </button>
        </div>
      </div>

      <div className="bg-gray-800 rounded-xl border border-gray-700 overflow-hidden">
         <div className="p-4 border-b border-gray-700 flex gap-4">
            <div className="relative flex-1">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 w-4 h-4" />
                <input 
                    type="text" 
                    placeholder="Search creators..." 
                    className="w-full bg-gray-900 border border-gray-600 rounded-lg pl-9 pr-4 py-2 text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                />
            </div>
         </div>
         <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
                <thead className="bg-gray-900 text-gray-400 uppercase font-medium border-b border-gray-700">
                    <tr>
                        <th className="px-6 py-3">Creator</th>
                        <th className="px-6 py-3">Stats</th>
                        <th className="px-6 py-3">Niche</th>
                        <th className="px-6 py-3 text-right">Actions</th>
                    </tr>
                </thead>
                <tbody className="divide-y divide-gray-700">
                    {filteredCreators.length === 0 ? (
                        <tr><td colSpan={4} className="px-6 py-8 text-center text-gray-500">No creators found.</td></tr>
                    ) : (
                        filteredCreators.map(creator => (
                            <tr key={creator.id} className="hover:bg-gray-750/50">
                                <td className="px-6 py-4">
                                    <div className="flex items-center gap-3">
                                        <div className="w-10 h-10 rounded-full bg-gray-700 flex items-center justify-center">
                                            <User className="w-5 h-5 text-gray-400" />
                                        </div>
                                        <div>
                                            <div className="font-bold text-white">{creator.name}</div>
                                            <div className="text-xs text-gray-500">@{creator.username}</div>
                                        </div>
                                    </div>
                                </td>
                                <td className="px-6 py-4 text-gray-300">
                                    <div className="flex flex-col gap-1 text-xs">
                                        <span>{creator.videosCount} Videos</span>
                                        <span className="text-gray-500">{creator.avgViews.toLocaleString()} Views</span>
                                    </div>
                                </td>
                                <td className="px-6 py-4 text-gray-400">
                                    <span className="bg-gray-900 px-2 py-1 rounded border border-gray-700 text-xs">
                                        {creator.niche}
                                    </span>
                                </td>
                                <td className="px-6 py-4 text-right">
                                    <div className="flex justify-end gap-2">
                                        <button onClick={() => handleDelete(creator.id, creator.name)} className="p-2 hover:bg-red-900/30 text-gray-400 hover:text-red-400 rounded transition-colors">
                                            <Trash2 className="w-4 h-4" />
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        ))
                    )}
                </tbody>
            </table>
         </div>
      </div>
    </div>
  );
};

export default CreatorList;